AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      CodeUri: ./functions/test
      Environment:
        Variables:
          CodeartifactAuthToken: '{{resolve:secretsmanager:CodeartifactAuthToken:SecretString:token}}'
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./functions/test
