AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  CodeartifactAuthToken:
    Type: String

Resources:
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      CodeUri: ./functions/test
      Environment:
        Variables:
          CodeartifactAuthToken: !Ref CodeartifactAuthToken
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./functions/test
